# action.yml
name: 'shhhhh corp'
description: 'run policies and break if it breaks'
branding:
  icon: 'hash'
  color: 'blue'
inputs:
  github_token:
    description: 'GH action temporary token.'
    default: ${{ github.token }}
  cause_build_to_fail:
    description: 'When a policy is not kept, should the whole build fail?'
    default: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.github_token }}
    - ${{ inputs.cause_build_to_fail }}
